apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nodejs-app
spec:
  selector:
    matchLabels:
      app: nodejs-app
  replicas: 3
  template:
    metadata:
      labels:
        app:  nodejs-app
    spec:
      containers:
      - name:  nodejs-app
        image:  assignment2:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort:  3000
          
      
